# This is a basic workflow to help you get started with Actions

name: CI

on:
  create:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step 1 - Create a temporary artifact bundle folder
        run: |
          mkdir bundle,
          cd bundle
        
      - name: Step 2 - Install deps
        run: |
          echo Install deps,
          npm i
      
      - name: Step 3 - Create bundle
        run: |
          echo Build bundle,
          npm run build,
          cd ..
    
      - name: Step 4 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: game-bundle
          path: bundle
