# This is a basic workflow to help you get started with Actions

name: CI

on:
  create:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step 1 - Install deps
        run: |
          cd bundle
          pwd
          npm i
      
      - name: Step 2 - Create bundle
        run: |
          npm run build
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: game-bundle
          path: dist
